version: '3'

services:
      django:
        image: django-image
        container_name: "django-container"
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
          - "8000:8000"
        volumes:
          - ./input.txt:/app/input.txt

