version: '3'

services:
      django:
        image: django-sgx-image
        container_name: "django-sgx-container"
        build: 
          context: .
        ports: 
          - "8000:8000"
        devices:
          - "/dev/sgx_enclave:/dev/sgx_enclave"
        # command: /usr/bin/python3 manage.py runserver 0.0.0.0:8000
        # command: /app/entrypoint.sh  
