version: '3'

services:
      django:
        image: django-sgx-image
        container_name: "django-sgx-container"
        build: 
          context: .
        ports: 
          - "8000:8000"
        devices:
          - "/dev/sgx_enclave:/dev/sgx_enclave"
        volumes:
          - ./input.txt:/app/input.txt
        command: python manage.py runserver 0.0.0.0:8000
